Improve cp scripts

diff --git a/.scripts/cpgen b/.scripts/cpgen
--- a/.scripts/cpgen
+++ b/.scripts/cpgen
@@ -3,7 +3,7 @@
 if [ ! "$1" ];
 then
 	echo "Missing argument [contest name] (eg. 650d2)";
-	exit;
+	exit 1;
 fi
 
 (ls template.cpp >> /dev/null 2>&1 &&
@@ -16,4 +16,5 @@ fi
 	cp -n ../template.cpp e.cpp &&
 	cp -n ../template.cpp f.cpp &&
 	echo "generated code successfully"; ) ||
-	echo "FAILED"
+	(echo "FAILED" &&
+	exit 1)
